image: node:16
stages:
  - build
  - test
  - deploy
  - create_pr
pages:
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn docs:build
    - yarn docs:build
  artifacts:
    paths:
      - public
  only:
    - main

create_github_pr:
  image: alpine/git
  stage: create_pr
  variables:
    SHELL: /bin/sh
  only:
    - main
  script:
  - >
    docker run --rm --entrypoint=/bin/sh alpine/git:v2.26.2 -c "
    apk add --no-cache curl jq &&
    git config --global user.name 'gaurav' &&
    git config --global user.email 'gauravsvikhe@gmail.com' &&
    git clone https://gvaccr:${GITHUB_ACCESS_TOKEN}@github.com/gvaccr/test.git &&
    cd test &&
    git checkout -b feature/new_branch &&
    git remote add gitlab https://gauravsvikhe:${GITLAB_ACCESS_TOKEN}@gitlab.com/gauravsvikhe/test_docs.git &&
    git fetch gitlab &&
    git merge gitlab/main &&
    git push origin feature/new_branch &&
    PR_DATA=\$(curl -s -X POST -H 'Authorization: token ${GITHUB_ACCESS_TOKEN}' -H 'Accept: application/vnd.github+json' https://api.github.com/repos/gvaccr/test/pulls -d '{\"title\": \"New PR from GitLab CI\", \"head\": \"feature/new_branch\", \"base\": \"main\"}') &&
    PR_URL=\$(echo \$PR_DATA | jq -r '.html_url') &&
    echo 'Pull Request created: \$PR_URL'"
